# Generated by Django 5.1.6 on 2025-03-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rely_invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relyinvoice',
            name='invoiced_amount',
        ),
    ]
