# Generated by Django 5.1.6 on 2025-03-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rely_invoice', '0002_remove_relyinvoice_invoiced_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relyinvoice',
            old_name='date_invoicedd',
            new_name='date_invoiced',
        ),
    ]
