# Generated by Django 5.1.6 on 2025-03-20 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rely_invoice', '0003_relyreassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='relycompleted',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relyinvoice',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relypaid',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relyproblem',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relyprocessed',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relyreassigned',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
