# Generated by Django 5.1.6 on 2025-03-25 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rely_invoice', '0006_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order',
            name='date_received',
        ),
        migrations.AddField(
            model_name='work_order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
