# Generated by Django 5.1.6 on 2025-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_calendarevent_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_field', models.CharField(max_length=200)),
                ('second_field', models.CharField(max_length=200)),
            ],
        ),
    ]
