# Generated by Django 5.1.6 on 2025-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
