# Generated by Django 5.1.6 on 2025-04-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_events', to='payment.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
