# Generated by Django 5.1.6 on 2025-04-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_calendarevent_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='parent_event',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='recurrence_count',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='recurrence_interval',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_frequency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
