# Generated by Django 5.1.6 on 2025-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_schedule_app_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_app_member',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
