# Generated by Django 5.1.6 on 2025-02-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
