# Generated by Django 5.1.6 on 2025-02-21 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
