# Generated by Django 5.1.6 on 2025-02-24 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
