# Generated by Django 5.1.6 on 2025-02-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_invoice_date_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
