# Generated by Django 5.1.6 on 2025-03-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_alter_journal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiced_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
