# Generated by Django 5.1.6 on 2025-03-05 13:40

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_invoice_days_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='belle_task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marvin_task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 5, 13, 40, 21, 515186, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
