# Generated by Django 5.1.6 on 2025-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0015_belle_task_date_created_marvin_task_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
