# Generated by Django 5.1.6 on 2025-03-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_ebay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebay',
            options={'verbose_name_plural': 'Ebay'},
        ),
    ]
