# Generated by Django 5.1.6 on 2025-03-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0019_globaltimer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalTimer',
        ),
    ]
