# Generated by Django 5.1.6 on 2025-03-18 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0020_delete_globaltimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Today Order',
            },
        ),
        migrations.AddField(
            model_name='ebay',
            name='date_pushed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
