# Generated by Django 5.1.6 on 2025-03-18 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0021_today_order_ebay_date_pushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='today_order',
            name='date_pushed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
