# Generated by Django 5.1.6 on 2025-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0022_today_order_date_pushed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='amount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
