# Generated by Django 5.1.6 on 2025-03-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0023_ebay_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay',
            name='order_number',
            field=models.CharField(blank=True, default='0.0', max_length=200, null=True),
        ),
    ]
