# Generated by Django 5.1.6 on 2025-03-28 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0024_alter_ebay_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('order_number', models.CharField(blank=True, default='0.0', max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.CharField(blank=True, max_length=500, null=True)),
                ('date_pushed', models.DateField(default=django.utils.timezone.now)),
                ('delivery_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Merchant',
            },
        ),
    ]
