# Generated by Django 5.1.6 on 2025-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0025_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
