# Generated by Django 5.1.6 on 2025-03-28 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0026_ebay_transaction_date_merchant_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebay',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='merchant',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
