# Generated by Django 5.1.6 on 2025-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0029_alter_merchant_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
