# Generated by Django 5.1.6 on 2025-04-04 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0033_work_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_pushed', models.DateField(default=django.utils.timezone.now)),
                ('delivery_time', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Amex',
            },
        ),
    ]
