# Generated by Django 5.1.6 on 2025-04-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0035_rename_delivery_time_amex_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amex',
            old_name='name',
            new_name='order_number',
        ),
    ]
