# Generated by Django 5.1.6 on 2025-04-09 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0036_rename_name_amex_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='us_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sent', models.CharField(blank=True, max_length=200, null=True)),
                ('date_pushed', models.DateField(default=django.utils.timezone.now)),
                ('transaction_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'US_BANK',
            },
        ),
    ]
