# Generated by Django 5.1.6 on 2025-04-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0038_remove_us_bank_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='us_bank',
            name='date_sent',
        ),
        migrations.AddField(
            model_name='us_bank',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
