# Generated by Django 5.1.6 on 2025-04-09 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0039_remove_us_bank_date_sent_us_bank_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='us_bank',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
